# Generated by Django 3.0.3 on 2020-02-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='passsword',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
