# Generated by Django 3.0.3 on 2020-03-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200308_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='passsword',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='poll',
            name='picture',
            field=models.ImageField(upload_to='poll_picture'),
        ),
    ]
