# Generated by Django 3.0.3 on 2020-03-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200310_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
