# Generated by Django 3.0.3 on 2020-03-10 14:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_duration_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duration_poll',
            name='id',
        ),
        migrations.AlterField(
            model_name='duration_poll',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='duration_poll',
            name='poll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Poll'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 21, 50, 24, 976063)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 21, 50, 24, 976063)),
        ),
    ]
