# Generated by Django 3.0.3 on 2020-03-10 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20200310_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duration_poll',
            old_name='poll',
            new_name='from_poll',
        ),
        migrations.AlterField(
            model_name='poll',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 22, 2, 57, 623440)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 22, 2, 57, 623440)),
        ),
    ]
