# Generated by Django 3.0.3 on 2020-03-10 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20200310_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 22, 13, 27, 10590)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 22, 13, 27, 10590)),
        ),
        migrations.DeleteModel(
            name='Duration_Poll',
        ),
    ]
